project:
  type: website
  render:
  - "*.qmd"
  - "*.md"
  - "!quiz/*"

knitr:
  opts_chunk:
    root.dir: '.'

website:
  title: "ETC5513: Collaborative and Reproducible Practices"
  site-url: "https://rcp.numbat.space"
  navbar:
    background: "#006dae"
    left:
      - href: index.qmd
        text: Home
        icon: house-fill
      - text: Schedule
        icon: calendar2-fill
        menu:
          - file: week1/index.qmd
            text: "Week 1: Introduction to collaborative and reproducible practices"
          - file: week2/index.qmd
            text: "Week 2: Reproducible reports using Quarto"
          - file: week3/index.qmd
            text: "Week 3: Introduction to version control systems: git and GitHub"
          - file: week4/index.qmd
            text: "Week 4: Reproducible reporting using Quarto, git and GitHub"
          - file: week5/index.qmd
            text: "Week 5: Deeper git knowledge, stashing and tools"
          - file: week6/index.qmd
            text: "Week 6: Reproducible reporting and version control systems"
          - file: week7/index.qmd
            text: "Week 7:	Workflows for reproducible data analysis"
          - text: "Week 8: No class (University Holiday)"
          - file: week9/index.qmd
            text: Referencing, large files, and GitHub Issues
          - file: week10/index.qmd
            text: Keeping environments separate and reproducible
          - week11/index.qmd
          - week12/index.qmd
      - text: Discussion
        icon: chat-fill
        href: "https://learning.monash.edu/mod/forum/view.php?id=1366128"
      - text: Moodle
        icon: mortarboard-fill
        href: "https://learning.monash.edu/course/view.php?id=10201"
    right:
      - icon: github
        href: https://github.com/numbats/rcp

date-format: "D MMMM YYYY"

format:
  html:
    theme: [cosmo, numbat.scss]
    highlight: textmate
    toc: true
    mainfont: "Fira Sans"
    html-math-method: katex
    include-in-header:
      file: header.html


execute:
  echo: false
  warning: false
  message: false